[[language]]
name = "r"
auto-format = true

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
roots = []
comment-token = "#"

[[language]]
name = "cpp"
language-servers = ["clangd"]

